name: Bug Report
description: Report an issue
title: "[Bug Report]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please describe the bug in detail
    validations:
      required: true
